name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: fritzprix/cbuild:0.0.2

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: make config DEFCONF=x86_x86_64_hosting
    - name: make
      run: make
    - name: make check
      run: make check

