INC-y+=./include/test
LIB-y+=pthread
SRC-y+=./source/test
OBJ-y+=cdsl_bstree_test\
		cdsl_heap_test\
		cdsl_list_test\
		cdsl_slist_test\
		cdsl_spltree_test\
		cdsl_nrbtree_test\
		cdsl_hashtree_test\
		nrbtree_benchmark
